select identifier from db721_chicken order by 1;
select * from db721_chicken order by 1;
select identifier, identifier from db721_chicken order by 1;
select identifier, age_weeks, farm_name from db721_chicken order by 1;
select identifier, farm_name, age_weeks, farm_name from db721_chicken order by 1;
select identifier from db721_chicken where identifier < 15721 order by 1;
select identifier, farm_name from db721_chicken where farm_name <> 'Cheep Birds' order by 1;
select identifier from db721_chicken where identifier > 15445 and identifier < 15721 order by 1;
select identifier, age_weeks from db721_chicken where age_weeks > 3 and farm_name = 'Breakfast Lunch Dinner' order by 1;
select identifier, farm_name from db721_chicken where age_weeks > 52 and weight_g > 2500 order by 1;
select * from db721_chicken where identifier > 15721 and identifier < 900 order by 1;
select * from db721_chicken where farm_name = 'Cheep Birds' and identifier = 1 and weight_model = 'GOMPERTZ' order by 1;
select * from db721_chicken where age_weeks < 50 and weight_g > 2000 and identifier > 15721 and farm_name <> 'Cheep Birds' and farm_name = 'Breakfast Lunch Dinner' order by 1;
select * from db721_chicken where farm_name > 'C' and age_weeks > 104 and identifier < 80000 order by 1;
select identifier, age_weeks, farm_name from db721_chicken where identifier > 9000000 order by 1;
select identifier, age_weeks, farm_name from db721_chicken where farm_name < 'bok' order by 1;
select identifier, age_weeks, farm_name from db721_chicken where sex = 'FEMALE' and age_weeks > 5 and identifier > 10 order by 1;
select identifier, farm_name from db721_chicken where sex = 'FEMALE' and age_weeks > 52 order by 1;
select count(*) from db721_chicken where sex = 'MALE' and age_weeks > 5 and weight_g > 1500 order by 1;
select c.farm_name from db721_chicken c, db721_farm f where c.notes = 'WOODY' and c.farm_name = f.farm_name group by c.farm_name order by 1;